### ISSUE TITLE
HDB Computation Processor Upgrade Potential Issue

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#16]
Something to keep an eye on with the roll out of the new CP with OpenDCS6.0 is that the upgrade changes  the table.column **cp_comp_ts_parm.interval** to **cp_comp_ts_parm.interval_abbr**. HDB POET failed after the initial upgrade in LC and we had to change the column name back for POET to work. Should we restructure the SQL that relies on this table.column in POET?

**Comment by ktarbet** [comment]
We could have a config file option so we can switch between test and production.  test could be for OpenDCS6.0
