### ISSUE TITLE
Excel-style data table snapping

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#18]
Hello, I have another request.   Could you add the ability to hold Shift + Ctrl + down arrow to select a column of data down to a missing value, like Excel does?  Currently if you hold Shift + Ctrl + down arrow POET selects down to the bottom of the column and includes missing values in the selection.

**Comment by ktarbet** [comment]
If this feature is packaged as a component -- that could be useful for other applications like HydrometTools.  Currently Hydromet tools uses a third-party software for the data editing grid.

**Comment by tjrocha** [comment]
This issue will be adressed in #35
