### ISSUE TITLE
Add upgrade button to the HDB POET interface

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#20]
Make it so that users can upgrade HDB POET from within HDB POET. Something like navigating to About > Check for Upgrades > Upgrade...

Requested by Boulder, CO Modeling Group.

**Comment by ktarbet** [comment]
I suggest providing a link to download the latest version in the about box (when applicable).   You could store the latest version string in github and compare that to the current version.

Based on my experience with coding my own auto-updaters in the past it is best to do something very simple, like provide a link to an installer.

**Comment by tjrocha** [comment]
Ok. I'll do that then. Thanks for the feedback!
