### ISSUE TITLE
Table to Excel bug

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#24]
Fix issue submitted by LC BCOO Water Accounting. Can be reproduced by:

1. querying monthly SDID 2908, 3158, 3160, 3159, and 23471.
2. going to the table tab
3. clicking on the Excel button

![image](https://cloud.githubusercontent.com/assets/8174126/26420351/2e8c638c-4077-11e7-9482-8a8b0e8878b6.png)

**Comment by tjrocha** [comment]
Can I please get a new incremented release for this critical bug fix @ktarbet?

**Comment by ktarbet** [comment]
yes.  But first there is a missing file  .HdbPoet\Upgrade.cs'.

**Comment by tjrocha** [comment]
ok. sorry about that. forgot to add it. should be fixed with e1f133f

**Comment by ktarbet** [comment]
Resource file "Upgrade.resx" cannot be found.

**Comment by tjrocha** [comment]
*sigh* i thought i caught all of them...

**Comment by ktarbet** [comment]
https://github.com/usbr/HdbPoet/releases/tag/v3.2.36

**Comment by tjrocha** [comment]
Bug fixed! thanks @ktarbet!

**Comment by tjrocha** [comment]
It looks like the installer file didn't have the bug fix since it was made to CsvFile,cs in the Reclamation.Core project. I moved the fix to an Hdb POET specific file. Please recompile a new installer @ktarbet. Thanks much!

**Comment by ktarbet** [comment]
https://github.com/usbr/HdbPoet/releases/tag/v3.2.37

**Comment by tjrocha** [comment]
Thanks @ktarbet
