### ISSUE TITLE
The down button isn't functioning as intended.

### ISSUE THREAD

**Issue by rclaytonrclayton** [usbr/HdbPoet#26]
There is an up and down arrow on the right side of the Home tab.  These are intended to allow the user to arrange the list of datasets selected in a user selected order.  While the Up arrow allows the user to move data sets up in the list, the Down arrow does not move the data set downward as intended.  The Down arrow function should be the opposite of the Up arrow function.  

I tried to attache a screenshot but this did not appear to go in as an image but rather as a URL.  Not sure why that is.  Any questions please call or email Rick at rclayton@usbr.gov or 801-524-3710. 

![image](https://user-images.githubusercontent.com/30149994/28167780-ffd1d0a0-6799-11e7-94b2-1986850babab.png)

**Comment by tjrocha** [comment]
This issue has been fixed in the code and will be included in the next release

**Comment by rclaytonrclayton** [comment]
Thanks Jon...That was fast.  Did I use the GitHub bug report system
correctly?

R


Rick Clayton

Bureau of Reclamation
Water Resources Group,
Resource Management Division

125 South State Street

Room 8100 (ATTN: UC-437)

Salt Lake City, UT 84138

work: 801-524-3710

cell: 801-641-8803


*"Non illegitimis carborundum"*

**Comment by tjrocha** [comment]
Yes you did. Thanks Rick!
