### ISSUE TITLE
Show Details for Modeled Data does not work

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#27]
On the table tab, right-clicking and selecting Show Details on the context menu does not work for data queried from the Modeled Tables.

**Comment by tjrocha** [comment]
Metadata does not show up because HDB does not store this type of metadata for data in the M-Tables. Made the Show Details result reflect this as shown below.

![image](https://user-images.githubusercontent.com/8174126/28392205-cc92da76-6c95-11e7-9975-925077107883.png)

**Comment by agilmore2** [comment]
Is the model run information already clearly available in the interface? If
not, at least the model run name could be useful.

**Comment by tjrocha** [comment]
Yes. The Model Run Name, Last Update Date, and Model Id are all shown via drop down menus for querying data from the M-Tables.

![image](https://user-images.githubusercontent.com/8174126/28392688-d7c7e02e-6c97-11e7-8ebc-ed4da9986677.png)
