### ISSUE TITLE
Analysis Tab

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#33]
Request for a new tab to quickly show historical analysis for a Series given an SDI and a date range. Request is to enable users to quickly see if data points are within reasonable historical and/or statistical bounds (Min/Max, IQR, etc). Request also calls for this tab to be modular in nature so different analyses can be performed on each Series.

This is very similar to Pisces' Time Series Analysis functionality. Should look into adapting the code that controls this in Pisces within POET. @ktarbet - thoughts on this?

**Comment by ktarbet** [comment]
I'm also trying to revamp Hydromet tools stats Tab.   Perhaps we can collaborate.  the purpose I'm seeking is things like 30 year averages, ranking years, etc.  the key features in the old Check program.

**Comment by tjrocha** [comment]
I would love to collaborate on this effort. Would you want to build in Hydromet Tools and I port it over to POET or build it in POET and you port it over to Hydromet Tools? Is the Hydromet Tools source code available on GitHub?

**Comment by ktarbet** [comment]
Yes,  Hydromet tools is under Pisces -- [HydrometTools](https://github.com/usbr/Pisces/tree/master/Applications/HydrometTools)   The start we have in Hydromet Tools is under Stats [Stats](https://github.com/usbr/Pisces/tree/master/Applications/HydrometTools/Stats)  Thanks @jhildreth1  for this initial code.

My dream would be to build  a framework that allows adding new statistics/displays.   Perhaps a screen with different analysis types as a list (sorta like pisces),  then specific UI and outputs for each statistical method.

**Comment by tjrocha** [comment]
This is pretty much what I'm envisioning. Start by directly porting over the Analysis code from Pisces but use the selected series from the POET Home tab. Once this is done, we can add more analysis options.

![image](https://user-images.githubusercontent.com/8174126/29947364-1416d836-8e5e-11e7-9b19-57380f371005.png)

**Comment by ktarbet** [comment]
@tjrocha  I really like this!    If we keep the 'generic' code in the Reclamation.TimeSeries.Forms and Reclamation.Timeseries area then we are sharing the code -- and life will be good.  Can you envision doing it that way?

That way if either you or I add a new statistical method, it automatically shows up in Both Pisces, Poet, and Hydromet Tools.

**Comment by tjrocha** [comment]
@ktarbet Yes, having the core analysis code in the TimeSeries Project is what I was initially envisioning. This way if you add Analysis options I get to use it as well and vice-versa. Between the two of us we can probably come up with all kinds of cool things...

I did have a question since we are thinking about moving in this direction. Would it make sense to have POET be an 'Application' within the larger Pisces codebase? This seems to be the way the Pisces App, Hydromet Tools, etc are configured to run right now.

**Comment by ktarbet** [comment]
I see advantage of Application, but also advantage of being separate.   How about thinking about this during the next week of commits and think about the implications.

**Comment by ktarbet** [comment]
Question to us:   How do we allow using Pisces Analysis code inside POET without doing major surgery on the Pisces code -- Here is one possible answer:

What if you have a sqlite pisces database (hdb-poet.pdb) behind the scenes to satisfy the requirements of the Pisces Engine?   That might get us started -- then any required refactoring will be more focused.

**Comment by tjrocha** [comment]
Would having a single hdb-poet.pdb instance work with multiple HDB-POET instances/windows? I'm assuming that we would have to dump the selected Series in the PDB and read it from there to make the Pisces Engine work; is this a correct assumption?

**Comment by ktarbet** [comment]
I would hope we could pass a SeriesList from Poet to the Analysis tool from any HDB instance.  Worst case is we have a layer of code that handles that transfer.   However, when we get the first beta working we will be able to make some changes to Pisces code, and perhaps remove the need for hdb-poet.pdb long term.  We could have a callback that asks POET -- "please hand me the series list"

**Comment by tjrocha** [comment]
I see, so we're really using the pdb as a 'calculator' of sorts given a SeriesList(). I like that!

**Comment by tjrocha** [comment]
Inorporated into master via PR #39
