### ISSUE TITLE
Convert DataGridView table to HydrometTools-style SpreadsheetGear

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#35]
Bought SpreadsheetGear license for LC HDB POET development. @ktarbet - Do you have a good sample codebase/use case for incorporating spreadsheet gear into C#? Thanks!

**Comment by ktarbet** [comment]
Yes,  and just as important this code below is used to *isolate* the third party component.


In other words the code below has spreadsheet gear specific code inside, but the return values are regular .net/C# objects.

https://github.com/usbr/Pisces/blob/master/TimeSeries.Excel/SpreadsheetGearExcel.cs
https://github.com/usbr/Pisces/blob/master/TimeSeries.Excel/SpreadsheetGearSeries.cs

I'm a huge fan of sharing code-- The assembly/project Reclamation.TimeSeries.Excel.csproj has these components.  If there is too much baggage in that project for you -- we can break this out into another project Reclamation.SpreadheetGear.csproj

**Comment by ktarbet** [comment]
In Hydromet tools the editing tool (getting more specific at this point) I fist abstracted out an interface to keep both a standard DataGridView and SpreadsheetGear as options and again to isolate code.   Here is the code:

Interface:

https://github.com/usbr/Pisces/blob/master/Applications/HydrometTools/ITimeSeriesSpreadsheet.cs

DataGrid version
https://github.com/usbr/Pisces/blob/master/Applications/HydrometTools/TimeSeriesSpreadsheet.cs

SG version

https://github.com/usbr/Pisces/blob/master/Applications/HydrometTools/TimeSeriesSpreadsheetSG.cs

This keeps the code *isolated* and sharable and allows for the future.

**Comment by tjrocha** [comment]
Recent bug with the latest Reclamation.Core and Reclamation.TimeSeries work has broken reference calls to NpoiExcel. Propose switching everything that relies on Excel within POET to SpreadSheetGear.

**Comment by ktarbet** [comment]
I agree it would be nice to have a single layer to read excel data.

You may need to reference  Reclamation.Windows.dll  NPOI has moved there.

**Comment by tjrocha** [comment]
Additional request from 2017 HDB User Group. Allow users to see/add/edit DATA_FLAGS on a per-TsPoint basis. This field is exposed via Table-TsPoint-right-click-ShowDetails.  If this field exists for the TsPoint, add the value as a 'comment' to the SG Cell.

**Comment by tjrocha** [comment]
Working implementation in [pre-release V3.4.0](https://github.com/usbr/HdbPoet/releases/tag/3.4.0)!

**Comment by tjrocha** [comment]
Installer shared with select users for testing and feedback.

**Comment by tjrocha** [comment]
90ce9de has more edits based on feedback

**Comment by tjrocha** [comment]
Closing issue. No further feedback received and testers are generally happy with the new features.
