### ISSUE TITLE
New data-cell coloring scheme: QA/QC

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#44]
Request from LC River Ops to add a new coloring scheme for data cells in the table tab. This is functionality that is originally in LC's Data Doctor and is used for quick visual data QA/QC efforts by River Operations. Envision having another button next to the 'validation' coloring button  for 'QA/QC'.

![image](https://user-images.githubusercontent.com/8174126/33491380-f894ecde-d66e-11e7-9bb1-2a4eca1ec52a.png)

Roadmap:
* GUI work - add 'QA/QC' button on main UI
* On log-in, check if required tables (ref_ext_site_data_map, ref_ext_site_data_map_keyval, & ref_interval_copy_limits) exist in selected HDB and toggle availability of the 'QA/QC' button
* Incorporate needed SQL in POET and build C# method to call it
* Build cell coloring methods based on value thresholds
* Wire 'QA/QC' button to loop through Series items in the table tab while calling the cell coloring methods
* Add 'QA/QC' cell colors to Legend UI

SQL to fetch coloring thresholds follow :
`
select 
  a.min_value_expected "ExpectedMinAlarm", 
  a.max_value_expected "ExpectedMaxAlarm", 
  a.min_value_cutoff "CutoffMinAlarm", 
  a.max_value_cutoff "CutoffMaxAlarm",
  c.key_value "RateOfChangeAlarm",
  d.key_value "RepeatAlarm"
from 
  ref_interval_copy_limits a,
  ref_ext_site_data_map b,
  ref_ext_site_data_map_keyval c,
  ref_ext_site_data_map_keyval d
where
  a.site_datatype_id = 2146
  and lower(a.interval) = 'hour'
  and a.site_datatype_id = b.hdb_site_datatype_id
  and a.interval = b.hdb_interval_name
  and b.mapping_id = c.mapping_id
  and lower(c.key_name) = 'rate of change limit'
  and b.mapping_id = d.mapping_id
  and lower(d.key_name) = 'repeat limit'
order by a.site_datatype_id;
`

**Comment by DeenaLarsen** [comment]
Please let me know what I need to do for the Help Doc and any other documentation on this issue. thanks!

**Comment by tjrocha** [comment]
Feature incorporated into version 3.6.0. Ready for user testing.

**Comment by tjrocha** [comment]
User testing underway in LC. Initial feedback all positive.

**Comment by DeenaLarsen** [comment]
Jon, when we have this, please talk me through it so I can add it to the help file. thanks

**Comment by tjrocha** [comment]
Hi Deena. The help file I think is very outdated with all the enhancements that we've added since it was last published in 2011. I think we are opting to maintain the online guide/wiki at https://github.com/usbr/HdbPoet/wiki rather than having a static document. @ktarbet - what are your thoughts on this?

**Comment by DeenaLarsen** [comment]
We are transitioning to a wiki/online help system, but I need to have an updated help version.  I think there is some confusion--I am talking about the help file for RWIS/RISE only--which we updated this November for Release 1.1  **https://water.usbr.gov/docs/RWIS_Help_File.pdf**

**Comment by tjrocha** [comment]
Oh, ok. This project, HDB POET, exists outside of and does not impact RWIS/RISE.

**Comment by DeenaLarsen** [comment]
Thanks. Glad to know I do not have to update the RWIS help file :)

**Comment by tjrocha** [comment]
included in v3.6.5 release
