### ISSUE TITLE
Hide/Remove Plot on the Table Tab

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#46]
Request the following change be implemented into the production version of HDB-POET.

From HDB=POET version 3.6.5.0, please completely remove the auto-displayed, embedded data plot from the table tab view.  Only show the spreadsheet view of the site-parameters that the user has selected on the table tab view.

The users will reserve the possibility to revisit this decision in the future to perhaps make the embedded plot displayable within the table tab but if we decide later to go this route the plot would have to be activated by the user (no auto-display).  

- R.Clayton

**Comment by ktarbet** [comment]
@tjrocha You may consider implementing this with config file setting to allow expert users an optional feature.

**Comment by tjrocha** [comment]
Will do. I might have this setting be visible to users via the help>options UI as well. Thanks @ktarbet!

**Comment by tjrocha** [comment]
Enhancement rolled into v3.6.6 release
