### ISSUE TITLE
can't access model data

### ISSUE THREAD

**Issue by beautah** [usbr/HdbPoet#59]
Can't access model data, the site list populates with sites but the datatypes won't drop down. 

Tested using model ID #2 - AOP, run id #3102, sDate - 09/01/2019, eDate - 09/01/2021, interval - month, site name - flamin, object type - reservoir

flaming gorge pops up in site list but the datatypes won't drop down

**Comment by beautah** [comment]
A temporary fix is to uncheck "show basic SDI information" under Help -> options

**Comment by tjrocha** [comment]
Updated installer file at https://github.com/usbr/HdbPoet/releases/tag/v3.6.10
