### ISSUE TITLE
Password Checking/Management Feature

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#60]
Edited email dated 14NOV2019 follows:

> Hi Jon,
> 
> I wonder if we might ask you for some time to develop a new feature into HDB POET... We would like HDB POET to have a simple password manager tool built into it.  I am thinking that it would live under the help tab... I would suggest it would live right below or perhaps inside the 'Options' option in the dropdown... And would say something like Password Manager
> 
> When the user clicks on Password Manager, a pop up window would come up where the user would select the HDB instance on the left from a dropdown.  Then in the center the user could type in database username.  Then on the right there could be 3 fields for passwords.  The top field would be labeled "current password"  The second field would be labeled "new password" and the third field would be labeled 'retype new password".  Then there would be a button in the center bottom that is labeled "Change Password"
> 
> When the user selects a database, enters a currently existing username and current password, then types in a new password (meeting all password rules described below) and then retypes that new password to match the first and activates the Change Password button, HDB POET would submit the proper sql back to the database to edit the users password as requested.
> 
> It would also be good to provide the password rules in this popup window so users know what their passwords need to include.
> 
> I think the password rules are:
> 1.  At least 12 characters
> 2.  At least 1 capital letter
> 3.  At least 1 lower-cased letter
> 4.  At least 1 number
> 5.  At least 1 special character
> 
> These should be the same as the AD passwords for LAN accounts so if I am missing any please add.
> 
> In addition to this functionality, when a user tries to login through HDB-POET and their password is expired, the HDB-POET session connection to HDB would receive a _ORA-28001:the password has expired_ message.  When HDB-POET receives this message from HDB, we would like HDB-POET to immediately open a dialogue window that tells the user their password is expired and provides them with the ability to change their password at that time.  Ideally the use would be taken directly into a dialogue window to change their password automatically.
> 
> And one other functionality we would like is this.  When a user tries to connect to an HDB database, if the user's password is within 12 days of expiring, the HDB-POET session connection to HDB will receive a _ORA-28002:the password will expire within X days_ message where X is the number of days before the password will expire..   When HDB-POET receives this message from HDB, we would like this message relayed to the user within a small pop-up dialogue window with a guide for the user for where the should go within HDB-POET to change their password.
> 
> Rick

**Comment by tjrocha** [comment]
Working. Tested by jrocha. Ready for user testing...

If password is to expire within 15 days, the messagebox below will show after successful log-in.
![image](https://user-images.githubusercontent.com/8174126/69378443-9a6ba000-0c6b-11ea-81ca-ecdcf97253d0.png)

To use the Password Management feature, users will have to go to Help > Password Management as shown below.
![image](https://user-images.githubusercontent.com/8174126/69378473-aeaf9d00-0c6b-11ea-9c63-8e29280616c4.png)

The user interface looks like this.
![image](https://user-images.githubusercontent.com/8174126/69378487-b8390500-0c6b-11ea-9368-e955a40998a9.png)

**Comment by tjrocha** [comment]
Oracle throws error with just 1 LCASE or UCASE character. Changed requirements to 2 characters for each required character. Tested and working...

**Comment by agilmore2** [comment]
The number of characters is a per site decision. Why are we reimplementing
this check locally rather than checking the database's reaction?

**Comment by tjrocha** [comment]
@agilmore2 - User request was to show pwd requirements on the UI. Implemented a real-time validator for the pwd in the message box so integrating the requirements into the code was necessary. I don't care either way... ;)

![image](https://user-images.githubusercontent.com/8174126/69460949-935b9500-0d32-11ea-9d94-79caa362334b.png)

**Comment by agilmore2** [comment]
Thanks.

**Comment by tjrocha** [comment]
Updated password validation policy to match DOI requirements.

![image](https://user-images.githubusercontent.com/8174126/69736183-3fb0c900-10ef-11ea-84c6-9fe69797b3e8.png)

**Comment by tjrocha** [comment]
New requirements. Go with: 

-  Must be 12 to 30 characters in length
-  Must have at least 2 special characters
-  Must have at least 2 capital letters
-  Must have at least 2 lower case letters
-  Must have at least 2 numbers
-  Cannot have more that 3 consecutive character types in a row
-  Cannot match old passwords used during previous year

**Comment by tjrocha** [comment]
Final accepted requirements:

- Must be at least 15 characters in length
- Must have at least 2 special characters
- Must have at least 2 upper case letters
- Must have at least 2 lower case letters
- Must have at least 2 numbers
- Cannot have more than 3 consecutive character types in a row
- Should differ from the previous password by at least 8 characters in the same position
