### ISSUE TITLE
Add a Pisces-style SQL viewer & command window as a new tab...

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbPoet#8]
Request was made by the HDB User Group during their 2016 meeting that a way to directly run SQL and interact with HDB would be helpful for users with moderate to advanced SQL skill levels. 

I suggested that we can try to port over this functionality from Pisces with the modifications below. HDB Users were made aware that this will only be for read-only purposes and not for full CRUD functionality like the rest of POET.
1. Add a side-menu with selectable SQL snippets to perform certain functions. Something like the Pisces equation within the Calculation Series builder but with pre-configured SQL commands. The intent is to have this section be modular so we can add other specialized SQL snippets as needed.
2. Have this new tab only be visible based on access levels defined in the REF_USER_GROUPS table.

![image](https://cloud.githubusercontent.com/assets/8174126/18174981/72406a20-7024-11e6-965a-7ff5f9189b5e.png)

**Comment by ktarbet** [comment]
If you double click the status bar this 'hidden' functionality is 'mostly' available in POET.

**Comment by tjrocha** [comment]
sneaky... that makes this much easier then...

**Comment by tjrocha** [comment]
Enhancement mock-up detailed in the attached PDF. This will be the final product that will be generated from this enhancement. 

[Proposed POET Enhancement.pdf](https://github.com/usbr/HdbPoet/files/457490/Proposed.POET.Enhancement.pdf)

**Comment by ktarbet** [comment]
If users have the ability to work with 'canned' SQL statements - you may also want a 'save' feature to save/add new 'canned' SQL commands.

**Comment by tjrocha** [comment]
Great suggestion. I will do just that.

**Comment by agilmore2** [comment]
How hard would it be to get a Linux build environment set up? Can POET run
in Linux now?

The first level requirement is for another data timeseries set, like
r_base, which is not as complicated as model data. The concern is adding
more complexity to the time series selection screen.

Perhaps an advanced mode toggle, or an addition to the Admin tab?

The queries should be relatively straightforward. The important pieces are
that the indexes on the r_base_archive are not as advanced.

The more advanced need is for summaries of the archive data for each data
point. This may be an application of the stored SQL that Jon mentioned.

Andrew

**Comment by ktarbet** [comment]
Today POET is windows but Linux is possible with some effort.  The Pisces libraries (behind poet) work fine on linux.  

https://github.com/usbr/Pisces/blob/master/build.sh

**Comment by tjrocha** [comment]
Fully functional test UI added via ad435753c15d82cdf2c47c1a2ec60536d8e878ce.
